"""empty message

Revision ID: 1a095dbd74e9
Revises: e0828d9d5a27
Create Date: 2016-06-15 21:43:27.551000

"""

# revision identifiers, used by Alembic.
revision = '1a095dbd74e9'
down_revision = 'e0828d9d5a27'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tagname', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tags_assoc',
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], )
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tags_assoc')
    op.drop_table('tags')
    ### end Alembic commands ###
