"""empty message

Revision ID: 21a579741ab6
Revises: feec45c79147
Create Date: 2016-08-14 10:57:06.090000

"""

# revision identifiers, used by Alembic.
revision = '21a579741ab6'
down_revision = 'feec45c79147'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('streak_updated', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'streak_updated')
    ### end Alembic commands ###
