"""empty message

Revision ID: 239258aab91a
Revises: dd08ad1d1c69
Create Date: 2016-07-09 18:26:08.118000

"""

# revision identifiers, used by Alembic.
revision = '239258aab91a'
down_revision = 'dd08ad1d1c69'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hide_difficulty', sa.Boolean(), nullable=True),
    sa.Column('repeat_solved_questions', sa.Boolean(), nullable=True),
    sa.Column('auto_load_questions', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_settings')
    ### end Alembic commands ###
