"""empty message

Revision ID: 25e16179690f
Revises: 8cd97632404f
Create Date: 2016-08-11 14:03:09.644000

"""

# revision identifiers, used by Alembic.
revision = '25e16179690f'
down_revision = '8cd97632404f'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_settings', sa.Column('hide_options', sa.Boolean(), nullable=True))
    op.drop_column('user_settings', 'hide_solutions')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_settings', sa.Column('hide_solutions', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_column('user_settings', 'hide_options')
    ### end Alembic commands ###
