"""empty message

Revision ID: 29e575f29564
Revises: cdbb044303d5
Create Date: 2016-07-04 10:04:08.536000

"""

# revision identifiers, used by Alembic.
revision = '29e575f29564'
down_revision = 'cdbb044303d5'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favourite_questions_assoc_obj',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'question_id')
    )
    op.drop_table('solved_questions_assoc')
    op.drop_table('favourite_question_assoc')
    op.drop_index('ix_questions_timestamp', table_name='questions')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_questions_timestamp', 'questions', ['timestamp'], unique=False)
    op.create_table('favourite_question_assoc',
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('question_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['question_id'], [u'questions.id'], name=u'favourite_question_assoc_ibfk_1'),
    sa.ForeignKeyConstraint(['user_id'], [u'users.id'], name=u'favourite_question_assoc_ibfk_2'),
    sa.PrimaryKeyConstraint('user_id', 'question_id'),
    mysql_default_charset=u'latin1',
    mysql_engine=u'InnoDB'
    )
    op.create_table('solved_questions_assoc',
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('question_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['question_id'], [u'questions.id'], name=u'solved_questions_assoc_ibfk_1'),
    sa.ForeignKeyConstraint(['user_id'], [u'users.id'], name=u'solved_questions_assoc_ibfk_2'),
    mysql_default_charset=u'latin1',
    mysql_engine=u'InnoDB'
    )
    op.drop_table('favourite_questions_assoc_obj')
    ### end Alembic commands ###
