"""empty message

Revision ID: 4a5374c48278
Revises: 239258aab91a
Create Date: 2016-07-12 11:39:19.530000

"""

# revision identifiers, used by Alembic.
revision = '4a5374c48278'
down_revision = '239258aab91a'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_settings', sa.Column('hide_solutions', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_settings', 'user_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.drop_column('user_settings', 'hide_solutions')
    ### end Alembic commands ###
