"""empty message

Revision ID: 5abc219f7fe4
Revises: 1a095dbd74e9
Create Date: 2016-06-18 02:12:07.706000

"""

# revision identifiers, used by Alembic.
revision = '5abc219f7fe4'
down_revision = '1a095dbd74e9'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_tags_assoc',
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    op.create_table('solved_questions_assoc',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    op.alter_column(u'tags', 'tagname',
               existing_type=mysql.VARCHAR(length=64),
               nullable=False)
    op.create_unique_constraint(None, 'tags', ['tagname'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tags', type_='unique')
    op.alter_column(u'tags', 'tagname',
               existing_type=mysql.VARCHAR(length=64),
               nullable=True)
    op.drop_table('solved_questions_assoc')
    op.drop_table('user_tags_assoc')
    ### end Alembic commands ###
