"""empty message

Revision ID: 5cb1a6acab3b
Revises: 4a5374c48278
Create Date: 2016-07-13 09:59:19.018000

"""

# revision identifiers, used by Alembic.
revision = '5cb1a6acab3b'
down_revision = '4a5374c48278'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('points',
    sa.Column('by_upvote', sa.Integer(), nullable=True),
    sa.Column('by_downvote', sa.Integer(), nullable=True),
    sa.Column('by_solution', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(u'user_settings', 'user_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.drop_table('points')
    ### end Alembic commands ###
