"""empty message

Revision ID: 69a30bd6b410
Revises: 5cb1a6acab3b
Create Date: 2016-07-13 16:57:06.356000

"""

# revision identifiers, used by Alembic.
revision = '69a30bd6b410'
down_revision = '5cb1a6acab3b'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_settings', 'user_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    ### end Alembic commands ###
