"""empty message

Revision ID: 7e04b251b97d
Revises: 8a0d0b3f3749
Create Date: 2016-07-05 21:08:17.026000

"""

# revision identifiers, used by Alembic.
revision = '7e04b251b97d'
down_revision = '8a0d0b3f3749'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('options', 'body',
               existing_type=mysql.TEXT(),
               nullable=False)
    op.add_column('questions', sa.Column('difficulty_index', sa.Float(), nullable=True))
    op.add_column('questions', sa.Column('reported_wrong_ques', sa.Integer(), nullable=True))
    op.add_column('solved_questions_assoc', sa.Column('attempted', sa.Integer(), nullable=True))
    op.add_column('solved_questions_assoc', sa.Column('solved', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('email', sa.String(length=128), nullable=True))
    op.add_column('users', sa.Column('score', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_column('users', 'score')
    op.drop_column('users', 'email')
    op.drop_column('solved_questions_assoc', 'solved')
    op.drop_column('solved_questions_assoc', 'attempted')
    op.drop_column('questions', 'reported_wrong_ques')
    op.drop_column('questions', 'difficulty_index')
    op.alter_column('options', 'body',
               existing_type=mysql.TEXT(),
               nullable=True)
    ### end Alembic commands ###
