"""empty message

Revision ID: 8a0d0b3f3749
Revises: 29e575f29564
Create Date: 2016-07-04 10:05:28.347000

"""

# revision identifiers, used by Alembic.
revision = '8a0d0b3f3749'
down_revision = '29e575f29564'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favourite_questions_assoc',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'question_id')
    )
    op.create_table('solved_questions_assoc',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'question_id')
    )
    op.drop_table('solved_questions_assoc_obj')
    op.drop_table('favourite_questions_assoc_obj')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favourite_questions_assoc_obj',
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('question_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('timestamp', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], [u'questions.id'], name=u'favourite_questions_assoc_obj_ibfk_1'),
    sa.ForeignKeyConstraint(['user_id'], [u'users.id'], name=u'favourite_questions_assoc_obj_ibfk_2'),
    sa.PrimaryKeyConstraint('user_id', 'question_id'),
    mysql_default_charset=u'latin1',
    mysql_engine=u'InnoDB'
    )
    op.create_table('solved_questions_assoc_obj',
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('question_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('timestamp', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], [u'questions.id'], name=u'solved_questions_assoc_obj_ibfk_1'),
    sa.ForeignKeyConstraint(['user_id'], [u'users.id'], name=u'solved_questions_assoc_obj_ibfk_2'),
    sa.PrimaryKeyConstraint('user_id', 'question_id'),
    mysql_default_charset=u'latin1',
    mysql_engine=u'InnoDB'
    )
    op.drop_table('solved_questions_assoc')
    op.drop_table('favourite_questions_assoc')
    ### end Alembic commands ###
