"""empty message

Revision ID: 98dd589d7024
Revises: 4f733ced1ae1
Create Date: 2016-07-30 14:13:19.890000

"""

# revision identifiers, used by Alembic.
revision = '98dd589d7024'
down_revision = '4f733ced1ae1'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('report_questions_assoc',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'question_id')
    )
    op.add_column(u'solved_questions_assoc', sa.Column('is_set_unsolved', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'solved_questions_assoc', 'is_set_unsolved')
    op.drop_table('report_questions_assoc')
    ### end Alembic commands ###
