"""empty message

Revision ID: cdbb044303d5
Revises: f3fcad830786
Create Date: 2016-07-03 18:35:02.045000

"""

# revision identifiers, used by Alembic.
revision = 'cdbb044303d5'
down_revision = 'f3fcad830786'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('solved_questions_assoc_obj',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'question_id')
    )
    op.drop_column(u'questions', 'upvotes')
    op.drop_column(u'questions', 'downvotes')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'questions', sa.Column('downvotes', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column(u'questions', sa.Column('upvotes', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_table('solved_questions_assoc_obj')
    ### end Alembic commands ###
