"""empty message

Revision ID: e0828d9d5a27
Revises: 1812378f5356
Create Date: 2016-06-14 16:45:50.885000

"""

# revision identifiers, used by Alembic.
revision = 'e0828d9d5a27'
down_revision = '1812378f5356'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('is_right', sa.Boolean(), nullable=True),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('options')
    ### end Alembic commands ###
