"""empty message

Revision ID: e8747ee0a07a
Revises: 239258aab91a
Create Date: 2016-07-11 15:03:46.713000

"""

# revision identifiers, used by Alembic.
revision = 'e8747ee0a07a'
down_revision = '239258aab91a'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('upvote_downvote_solutions_assoc',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('solution_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('is_upvote', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['solution_id'], ['solutions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'solution_id')
    )
    op.alter_column(u'user_settings', 'user_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(u'user_settings', 'user_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.drop_table('upvote_downvote_solutions_assoc')
    ### end Alembic commands ###
