"""empty message

Revision ID: feec45c79147
Revises: 25e16179690f
Create Date: 2016-08-13 11:56:41.760000

"""

# revision identifiers, used by Alembic.
revision = 'feec45c79147'
down_revision = '25e16179690f'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'reported_wrong_ques')
    op.add_column('tags', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('streak', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'streak')
    op.drop_column('tags', 'description')
    op.add_column('questions', sa.Column('reported_wrong_ques', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    ### end Alembic commands ###
